apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-mine-dagpenger-frontend
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dp-mine-dagpenger-frontend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{ image }}
  port: 3000
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: SELF_URL
      value: {{ ingress }}
    - name: DEKORATOR_URL
      value: {{ dekorator.url }}
    - name: DEKORATOR_ENV
      value: {{ dekorator.env }}
    - name: DP_INNSYN_URL
      value: http://dp-innsyn
    - name: DP_SOKNADSDIALOG_URL
      value: {{ soknadsdialog.ingress }}
    - name: PAW_ARBEIDSSOEKERREGISTERET_URL
      value: {{ pawArbeidssoekerregisteretUrl }}
  ingresses:
    - {{ ingress }}
  accessPolicy:
    outbound:
      external:
        - host: rt6o382n.apicdn.sanity.io
        - host: www.nav.no
        - host: dekoratoren.dev.nav.no
      rules:
        - application: dp-innsyn
        - application: paw-arbeidssoekerregisteret-api-oppslag
          namespace: paw
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: {{ idporten.level }}
      autoLogin: true
  tokenx:
    enabled: true
