apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-mine-dagpenger-frontend
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dp-mine-dagpenger-frontend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: "{{ image }}"
  port: 3000
  liveness:
    path: "/api/internal/isalive"
    initialDelay: 15
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: "/api/internal/isready"
    initialDelay: 15
    timeout: 1
  prometheus:
    path: "/api/internal/isready"
    enabled: true
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: BASE_PATH
      value: "{{ base_path }}"
    - name: SELF_URL
      value: "{{ ingress }}"
    - name: DEKORATOR_ENV
      value: "{{ dekorator.env }}"
    - name: DP_INNSYN_URL
      value: http://dp-innsyn
    - name: DP_SOKNADSDIALOG_URL
      value: "{{ soknadsdialog.ingress }}"
    - name: PAW_ARBEIDSSOEKERREGISTERET_URL
      value: "{{ paw_arbeidssoekerregisteret_url }}"
    - name: OKONOMI_KONTOREGISTER_URL
      value: "{{ okonomi_kontoregister_url }}"
    - name: SAF_URL
      value: "{{ saf.url }}"
    - name: SAF_CLUSTER
      value: "{{saf.cluster}}"
    - name: SAF_SCOPE
      value: "{{ saf.scope }}"
    - name: APP_ENV
      value: "{{ app_env }}"
    - name: UXSIGNALS_ENABLED
      value: "{{ uxsignals.enabled }}"
    - name: UXSIGNALS_MODE
      value: "{{ uxsignals.mode }}"
    - name: SANITY_DATASET
      value: "{{ sanity_dataset }}"
    - name: UNLEASH_SERVER_API_URL
      value: "{{ unleash.server_api_url }}"
    - name: FARO_URL
      value: "{{ faro_url }}"

  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
  accessPolicy:
    outbound:
      external:
        - host: rt6o382n.apicdn.sanity.io
        - host: www.nav.no
        - host: dekoratoren.dev.nav.no
        - host: dagpenger-unleash-api.nav.cloud.nais.io
        - host: "{{ saf.ingress }}"
      rules:
        - application: dp-innsyn
        - application: paw-arbeidssoekerregisteret-api-oppslag-v2
          namespace: paw
        - application: sokos-kontoregister-person
          namespace: okonomi
        - application: nav-dekoratoren
          namespace: personbruker
        - application: safselvbetjening
          namespace: teamdokumenthandtering
          cluster: "{{ saf.cluster }}"
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  tokenx:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
