// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/arbeid/dagpenger/mine-dagpenger": {
    params: {};
  };
  "/arbeid/dagpenger/mine-dagpenger/api/hent-dokument/:journalpostId/:dokumentInfoId": {
    params: {
      "journalpostId": string;
      "dokumentInfoId": string;
    };
  };
  "/api/internal/isalive": {
    params: {};
  };
  "/api/internal/isready": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/arbeid/dagpenger/mine-dagpenger" | "/arbeid/dagpenger/mine-dagpenger/api/hent-dokument/:journalpostId/:dokumentInfoId" | "/api/internal/isalive" | "/api/internal/isready";
  };
  "routes/arbeid.dagpenger.mine-dagpenger.tsx": {
    id: "routes/arbeid.dagpenger.mine-dagpenger";
    page: "/arbeid/dagpenger/mine-dagpenger" | "/arbeid/dagpenger/mine-dagpenger/api/hent-dokument/:journalpostId/:dokumentInfoId";
  };
  "routes/arbeid.dagpenger.mine-dagpenger.api.hent-dokument.$journalpostId.$dokumentInfoId.ts": {
    id: "routes/arbeid.dagpenger.mine-dagpenger.api.hent-dokument.$journalpostId.$dokumentInfoId";
    page: "/arbeid/dagpenger/mine-dagpenger/api/hent-dokument/:journalpostId/:dokumentInfoId";
  };
  "routes/api.internal.isalive.ts": {
    id: "routes/api.internal.isalive";
    page: "/api/internal/isalive";
  };
  "routes/api.internal.isready.ts": {
    id: "routes/api.internal.isready";
    page: "/api/internal/isready";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};